// User data
export const mockUserData = {
  name: "Gopal Agarwal",
  email: "gopal.ag0224@gmail.com",
  role: "Student",
  avatar: "/placeholder.svg?height=40&width=40",
  streakDays: 12,
  stats: {
    totalStudyHours: 87,
    coursesInProgress: 4,
    conceptsMastered: 32,
  },
  goals: [
    {
      id: "goal1",
      title: "Pass Machine Learning Certification",
      description: "Complete all required modules and pass the final exam",
      progress: 65,
      startDate: "April 10, 2025",
      dueDate: "June 15, 2025",
    },
    {
      id: "goal2",
      title: "Complete Data Structures Course",
      description: "Finish all lectures and assignments",
      progress: 42,
      startDate: "May 1, 2025",
      dueDate: "July 30, 2025",
    },
    {
      id: "goal3",
      title: "Build Portfolio Project",
      description: "Create a full-stack web application",
      progress: 25,
      startDate: "May 5, 2025",
      dueDate: "August 10, 2025",
    },
  ],
}

// Today's schedule
export const mockTodaySchedule = [
  {
    id: "schedule1",
    time: "9:00 AM - 10:30 AM",
    title: "Machine Learning: Neural Networks",
    duration: "1h 30m",
    completed: true,
    type: "study",
  },
  {
    id: "schedule2",
    time: "10:45 AM - 11:15 AM",
    title: "Quick Quiz: Neural Network Basics",
    duration: "30m",
    completed: true,
    type: "quiz",
  },
  {
    id: "schedule3",
    time: "11:15 AM - 11:45 AM",
    title: "Break & Review",
    duration: "30m",
    completed: false,
    type: "break",
  },
  {
    id: "schedule4",
    time: "12:00 PM - 1:30 PM",
    title: "Data Structures: Binary Trees",
    duration: "1h 30m",
    completed: false,
    type: "study",
  },
  {
    id: "schedule5",
    time: "2:00 PM - 3:00 PM",
    title: "Flashcard Review: SQL Concepts",
    duration: "1h",
    completed: false,
    type: "review",
  },
]

// Recent activity
export const mockRecentActivity = [
  {
    id: "activity1",
    type: "completed",
    title: "Completed Neural Networks Module",
    timestamp: "Today, 10:30 AM",
    details: "Finished all lectures and exercises",
  },
  {
    id: "activity2",
    type: "quiz",
    title: "Scored 85% on Neural Networks Quiz",
    timestamp: "Today, 11:15 AM",
    details: "12/14 questions correct",
  },
  {
    id: "activity3",
    type: "started",
    title: "Started Binary Trees Module",
    timestamp: "Today, 12:00 PM",
  },
  {
    id: "activity4",
    type: "achievement",
    title: "Earned 'Consistent Learner' Badge",
    timestamp: "Today, 9:00 AM",
    details: "Studied for 7 consecutive days",
  },
  {
    id: "activity5",
    type: "completed",
    title: "Completed Database Normalization Assignment",
    timestamp: "Yesterday, 4:15 PM",
  },
]

// Course catalog
export const mockCourses = [
  {
    id: "course1",
    title: "Machine Learning Fundamentals",
    description: "Learn the basics of machine learning algorithms and applications",
    category: "Computer Science",
    difficulty: "Intermediate",
    estimatedHours: 45,
    progress: 65,
    image: "/placeholder.svg?height=200&width=300",
    instructor: "Dr. Sarah Chen",
    tags: ["AI", "Python", "Data Science"],
    keyTopics: ["Supervised Learning", "Neural Networks", "Decision Trees", "Model Evaluation"],
  },
  {
    id: "course2",
    title: "Data Structures & Algorithms",
    description: "Master essential data structures and algorithm design techniques",
    category: "Computer Science",
    difficulty: "Intermediate",
    estimatedHours: 60,
    progress: 42,
    image: "/placeholder.svg?height=200&width=300",
    instructor: "Prof. James Wilson",
    tags: ["Algorithms", "Java", "Problem Solving"],
    keyTopics: ["Arrays & Linked Lists", "Trees & Graphs", "Sorting Algorithms", "Dynamic Programming"],
  },
  {
    id: "course3",
    title: "Database Systems",
    description: "Understand relational databases, SQL, and database design",
    category: "Computer Science",
    difficulty: "Beginner",
    estimatedHours: 30,
    progress: 90,
    image: "/placeholder.svg?height=200&width=300",
    instructor: "Dr. Michael Rodriguez",
    tags: ["SQL", "Database Design", "Normalization"],
    keyTopics: ["Relational Model", "SQL Queries", "Normalization", "Transaction Processing"],
  },
  {
    id: "course4",
    title: "Web Development with React",
    description: "Build modern web applications with React and related technologies",
    category: "Web Development",
    difficulty: "Intermediate",
    estimatedHours: 50,
    progress: 25,
    image: "/placeholder.svg?height=200&width=300",
    instructor: "Emma Thompson",
    tags: ["React", "JavaScript", "Frontend"],
    keyTopics: ["React Components", "State Management", "Hooks", "Performance Optimization"],
  },
  {
    id: "course5",
    title: "Calculus I",
    description: "Introduction to differential and integral calculus",
    category: "Mathematics",
    difficulty: "Intermediate",
    estimatedHours: 40,
    progress: 10,
    image: "/placeholder.svg?height=200&width=300",
    instructor: "Prof. Robert Chang",
    tags: ["Mathematics", "Calculus", "Functions"],
    keyTopics: ["Limits & Continuity", "Derivatives", "Applications of Derivatives", "Integrals"],
  },
  {
    id: "course6",
    title: "Introduction to Artificial Intelligence",
    description: "Explore the foundations of AI and its applications",
    category: "Computer Science",
    difficulty: "Advanced",
    estimatedHours: 55,
    progress: 5,
    image: "/placeholder.svg?height=200&width=300",
    instructor: "Dr. Alan Turing",
    tags: ["AI", "Machine Learning", "Neural Networks"],
    keyTopics: ["Search Algorithms", "Knowledge Representation", "Machine Learning", "Natural Language Processing"],
  },
  {
    id: "course7",
    title: "Business Analytics",
    description: "Learn to analyze business data for strategic decision making",
    category: "Business",
    difficulty: "Intermediate",
    estimatedHours: 35,
    progress: 0,
    image: "/placeholder.svg?height=200&width=300",
    instructor: "Prof. Lisa Johnson",
    tags: ["Analytics", "Business Intelligence", "Data Visualization"],
    keyTopics: ["Descriptive Analytics", "Predictive Analytics", "Data Visualization", "Business Intelligence Tools"],
  },
  {
    id: "course8",
    title: "Cybersecurity Fundamentals",
    description: "Understand core concepts in information security",
    category: "Computer Science",
    difficulty: "Beginner",
    estimatedHours: 25,
    progress: 0,
    image: "/placeholder.svg?height=200&width=300",
    instructor: "Mark Williams",
    tags: ["Security", "Networking", "Cryptography"],
    keyTopics: ["Security Principles", "Cryptography", "Network Security", "Security Policies"],
  },
]

// Knowledge graph data
export const mockKnowledgeGraph = {
  nodes: [
    { id: "1", label: "Machine Learning", group: "AI", mastery: 75 },
    { id: "2", label: "Neural Networks", group: "AI", mastery: 65 },
    { id: "3", label: "Deep Learning", group: "AI", mastery: 40 },
    { id: "4", label: "Supervised Learning", group: "AI", mastery: 80 },
    { id: "5", label: "Unsupervised Learning", group: "AI", mastery: 60 },
    { id: "6", label: "Reinforcement Learning", group: "AI", mastery: 30 },
    { id: "7", label: "Data Structures", group: "CS", mastery: 70 },
    { id: "8", label: "Arrays", group: "CS", mastery: 90 },
    { id: "9", label: "Linked Lists", group: "CS", mastery: 85 },
    { id: "10", label: "Trees", group: "CS", mastery: 60 },
    { id: "11", label: "Binary Trees", group: "CS", mastery: 55 },
    { id: "12", label: "Graphs", group: "CS", mastery: 45 },
    { id: "13", label: "Algorithms", group: "CS", mastery: 65 },
    { id: "14", label: "Sorting", group: "CS", mastery: 80 },
    { id: "15", label: "Searching", group: "CS", mastery: 75 },
    { id: "16", label: "Dynamic Programming", group: "CS", mastery: 40 },
    { id: "17", label: "Databases", group: "CS", mastery: 85 },
    { id: "18", label: "SQL", group: "CS", mastery: 90 },
    { id: "19", label: "Normalization", group: "CS", mastery: 70 },
    { id: "20", label: "Transactions", group: "CS", mastery: 60 },
    { id: "21", label: "Web Development", group: "Web", mastery: 75 },
    { id: "22", label: "HTML", group: "Web", mastery: 95 },
    { id: "23", label: "CSS", group: "Web", mastery: 85 },
    { id: "24", label: "JavaScript", group: "Web", mastery: 80 },
    { id: "25", label: "React", group: "Web", mastery: 70 },
    { id: "26", label: "Redux", group: "Web", mastery: 50 },
    { id: "27", label: "Node.js", group: "Web", mastery: 65 },
    { id: "28", label: "Express", group: "Web", mastery: 60 },
    { id: "29", label: "Calculus", group: "Math", mastery: 55 },
    { id: "30", label: "Limits", group: "Math", mastery: 70 },
    { id: "31", label: "Derivatives", group: "Math", mastery: 65 },
    { id: "32", label: "Integrals", group: "Math", mastery: 45 },
  ],
  links: [
    { source: "1", target: "2" },
    { source: "1", target: "4" },
    { source: "1", target: "5" },
    { source: "1", target: "6" },
    { source: "2", target: "3" },
    { source: "4", target: "2" },
    { source: "7", target: "8" },
    { source: "7", target: "9" },
    { source: "7", target: "10" },
    { source: "7", target: "12" },
    { source: "10", target: "11" },
    { source: "13", target: "14" },
    { source: "13", target: "15" },
    { source: "13", target: "16" },
    { source: "17", target: "18" },
    { source: "17", target: "19" },
    { source: "17", target: "20" },
    { source: "21", target: "22" },
    { source: "21", target: "23" },
    { source: "21", target: "24" },
    { source: "24", target: "25" },
    { source: "25", target: "26" },
    { source: "24", target: "27" },
    { source: "27", target: "28" },
    { source: "29", target: "30" },
    { source: "29", target: "31" },
    { source: "29", target: "32" },
    { source: "30", target: "31" },
    { source: "31", target: "32" },
    { source: "1", target: "13" },
    { source: "3", target: "6" },
    { source: "13", target: "7" },
    { source: "24", target: "18" },
  ],
}

// Flashcard data
export const mockFlashcards = [
  {
    id: "card1",
    front: "What is a Neural Network?",
    back: "A computational model inspired by the human brain, consisting of interconnected nodes (neurons) that process and transmit information.",
    category: "Machine Learning",
    lastReviewed: "2025-05-10",
    nextReview: "2025-05-17",
    difficulty: "medium",
    mastery: 3,
  },
  {
    id: "card2",
    front: "Explain Big O Notation",
    back: "A mathematical notation that describes the limiting behavior of a function when the argument tends towards a particular value or infinity. In computer science, it's used to classify algorithms according to their time or space complexity.",
    category: "Algorithms",
    lastReviewed: "2025-05-12",
    nextReview: "2025-05-15",
    difficulty: "hard",
    mastery: 2,
  },
  {
    id: "card3",
    front: "What is Database Normalization?",
    back: "The process of structuring a relational database to reduce data redundancy and improve data integrity by organizing fields and tables to ensure that their dependencies are properly enforced.",
    category: "Databases",
    lastReviewed: "2025-05-08",
    nextReview: "2025-05-18",
    difficulty: "medium",
    mastery: 4,
  },
  {
    id: "card4",
    front: "Define React Hooks",
    back: "Functions that let you use state and other React features without writing a class. They allow you to reuse stateful logic between components.",
    category: "Web Development",
    lastReviewed: "2025-05-14",
    nextReview: "2025-05-16",
    difficulty: "easy",
    mastery: 4,
  },
  {
    id: "card5",
    front: "What is the Chain Rule in Calculus?",
    back: "A formula for computing the derivative of a composite function. If f(x) = g(h(x)), then f'(x) = g'(h(x)) · h'(x).",
    category: "Mathematics",
    lastReviewed: "2025-05-05",
    nextReview: "2025-05-15",
    difficulty: "hard",
    mastery: 2,
  },
  {
    id: "card6",
    front: "Explain SQL JOIN types",
    back: "INNER JOIN: Returns records with matching values in both tables.\nLEFT JOIN: Returns all records from the left table and matched records from the right table.\nRIGHT JOIN: Returns all records from the right table and matched records from the left table.\nFULL JOIN: Returns all records when there is a match in either left or right table.",
    category: "Databases",
    lastReviewed: "2025-05-11",
    nextReview: "2025-05-16",
    difficulty: "medium",
    mastery: 3,
  },
  {
    id: "card7",
    front: "What is a Binary Search Tree?",
    back: "A tree data structure where each node has at most two children (left and right), and for each node, all elements in the left subtree are less than the node, and all elements in the right subtree are greater.",
    category: "Data Structures",
    lastReviewed: "2025-05-09",
    nextReview: "2025-05-17",
    difficulty: "medium",
    mastery: 3,
  },
  {
    id: "card8",
    front: "Define Gradient Descent",
    back: "An optimization algorithm used to minimize a function by iteratively moving in the direction of steepest descent as defined by the negative of the gradient.",
    category: "Machine Learning",
    lastReviewed: "2025-05-13",
    nextReview: "2025-05-18",
    difficulty: "hard",
    mastery: 2,
  },
]

// Analytics data
export const mockAnalytics = {
  studyTime: {
    daily: [2.5, 1.8, 3.2, 2.0, 1.5, 2.8, 3.5],
    weekly: [12, 15, 10, 18, 14, 16, 17, 13],
    monthly: [45, 52, 60, 48, 65],
  },
  subjectDistribution: [
    { name: "Machine Learning", value: 35 },
    { name: "Data Structures", value: 25 },
    { name: "Databases", value: 20 },
    { name: "Web Development", value: 15 },
    { name: "Mathematics", value: 5 },
  ],
  masteryProgress: {
    dates: ["Jan", "Feb", "Mar", "Apr", "May"],
    values: [10, 18, 25, 32, 40],
  },
  quizScores: [
    { name: "Neural Networks", score: 85 },
    { name: "Binary Trees", score: 72 },
    { name: "SQL Basics", score: 95 },
    { name: "React Hooks", score: 88 },
    { name: "Calculus I", score: 65 },
  ],
  strengths: ["SQL", "Web Fundamentals", "Supervised Learning"],
  weaknesses: ["Binary Trees", "Calculus", "Reinforcement Learning"],
  predictions: {
    examReadiness: 72,
    timeToCompletion: "6 weeks",
    recommendedFocus: ["Binary Trees", "Calculus", "Deep Learning"],
  },
}

// Study plan data
export const mockStudyPlan = {
  weeklySchedule: [
    {
      day: "Monday",
      sessions: [
        {
          id: "mon1",
          time: "9:00 AM - 10:30 AM",
          subject: "Machine Learning",
          topic: "Neural Networks",
          type: "study",
        },
        {
          id: "mon2",
          time: "11:00 AM - 12:00 PM",
          subject: "Data Structures",
          topic: "Binary Trees",
          type: "study",
        },
        {
          id: "mon3",
          time: "2:00 PM - 3:00 PM",
          subject: "Databases",
          topic: "SQL Joins",
          type: "practice",
        },
      ],
    },
    {
      day: "Tuesday",
      sessions: [
        {
          id: "tue1",
          time: "9:00 AM - 10:00 AM",
          subject: "Mathematics",
          topic: "Calculus: Derivatives",
          type: "study",
        },
        {
          id: "tue2",
          time: "10:30 AM - 11:30 AM",
          subject: "Machine Learning",
          topic: "Supervised Learning",
          type: "quiz",
        },
        {
          id: "tue3",
          time: "1:00 PM - 2:30 PM",
          subject: "Web Development",
          topic: "React Components",
          type: "project",
        },
      ],
    },
    {
      day: "Wednesday",
      sessions: [
        {
          id: "wed1",
          time: "9:00 AM - 10:30 AM",
          subject: "Data Structures",
          topic: "Graph Algorithms",
          type: "study",
        },
        {
          id: "wed2",
          time: "11:00 AM - 12:00 PM",
          subject: "Machine Learning",
          topic: "Neural Networks",
          type: "review",
        },
        {
          id: "wed3",
          time: "2:00 PM - 3:30 PM",
          subject: "Databases",
          topic: "Normalization",
          type: "study",
        },
      ],
    },
    {
      day: "Thursday",
      sessions: [
        {
          id: "thu1",
          time: "9:00 AM - 10:00 AM",
          subject: "Web Development",
          topic: "State Management",
          type: "study",
        },
        {
          id: "thu2",
          time: "10:30 AM - 12:00 PM",
          subject: "Mathematics",
          topic: "Integrals",
          type: "study",
        },
        {
          id: "thu3",
          time: "1:00 PM - 2:00 PM",
          subject: "Data Structures",
          topic: "Binary Trees",
          type: "quiz",
        },
      ],
    },
    {
      day: "Friday",
      sessions: [
        {
          id: "fri1",
          time: "9:00 AM - 10:30 AM",
          subject: "Machine Learning",
          topic: "Deep Learning",
          type: "study",
        },
        {
          id: "fri2",
          time: "11:00 AM - 12:30 PM",
          subject: "Databases",
          topic: "SQL Practice",
          type: "practice",
        },
        {
          id: "fri3",
          time: "2:00 PM - 4:00 PM",
          subject: "Project Work",
          topic: "Portfolio Project",
          type: "project",
        },
      ],
    },
    {
      day: "Saturday",
      sessions: [
        {
          id: "sat1",
          time: "10:00 AM - 11:30 AM",
          subject: "Review Session",
          topic: "Weekly Concepts",
          type: "review",
        },
        {
          id: "sat2",
          time: "1:00 PM - 2:30 PM",
          subject: "Practice Problems",
          topic: "Mixed Topics",
          type: "practice",
        },
      ],
    },
    {
      day: "Sunday",
      sessions: [
        {
          id: "sun1",
          time: "11:00 AM - 12:30 PM",
          subject: "Planning",
          topic: "Next Week Preparation",
          type: "planning",
        },
      ],
    },
  ],
  milestones: [
    {
      id: "milestone1",
      title: "Complete Neural Networks Module",
      dueDate: "May 25, 2025",
      progress: 65,
    },
    {
      id: "milestone2",
      title: "Finish Data Structures Course",
      dueDate: "June 15, 2025",
      progress: 42,
    },
    {
      id: "milestone3",
      title: "Submit Database Project",
      dueDate: "June 30, 2025",
      progress: 25,
    },
    {
      id: "milestone4",
      title: "Pass Machine Learning Certification",
      dueDate: "July 15, 2025",
      progress: 30,
    },
  ],
}
